eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
server:
  port: 8095
spring:
  application:
    name: service-feign
    thymeleaf:
      cache: false
      mode: LEGACYHTML5
      prefix: classpath:templates/
      content-type: text/html
      encoding: UTF-8
    # 数据库链接
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.31.8:3306/edu
      username: root
      password: root




